{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fff2bb25",
   "metadata": {},
   "outputs": [],
   "source": [
    "from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup\n",
    "from telegram.ext import ContextTypes\n",
    "from datetime import datetime, timedelta\n",
    "import json\n",
    "import logging\n",
    "\n",
    "from database.session import SessionLocal\n",
    "from database import crud\n",
    "from shared.config import settings\n",
    "\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /start\"\"\"\n",
    "    user = update.effective_user\n",
    "    \n",
    "    # Сохраняем пользователя\n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        crud.add_or_update_user(\n",
    "            db,\n",
    "            telegram_id=user.id,\n",
    "            username=user.username,\n",
    "            is_admin=user.id in settings.ADMIN_IDS\n",
    "        )\n",
    "    finally:\n",
    "        db.close()\n",
    "    \n",
    "    await update.message.reply_text(\n",
    "        f\"👋 Привет, {user.first_name}!\\n\\n\"\n",
    "        f\"Я бот для доступа к данным водителей Яндекс.Такси.\\n\\n\"\n",
    "        f\"📋 *Доступные команды:*\\n\"\n",
    "        f\"/stats - статистика по водителям\\n\"\n",
    "        f\"/top - топ водителей по заказам\\n\"\n",
    "        f\"/search <имя> - поиск водителя\\n\"\n",
    "        f\"/new - новые водители (последние 30 дней)\\n\"\n",
    "        f\"/status <working/not_working/fired> - водители по статусу\\n\"\n",
    "        f\"/driver <id> - информация о конкретном водителе\\n\"\n",
    "        f\"/recent - последние обновления\\n\"\n",
    "        f\"/help - подробная справка\",\n",
    "        parse_mode='Markdown'\n",
    "    )\n",
    "\n",
    "async def get_stats(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /stats - статистика\"\"\"\n",
    "    await update.message.reply_text(\"📊 Собираю статистику...\")\n",
    "    \n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        stats = crud.get_driver_statistics(db)\n",
    "        \n",
    "        response = (\n",
    "            \"📈 *Статистика водителей:*\\n\\n\"\n",
    "            f\"👥 *Всего:* {stats['total']}\\n\"\n",
    "            f\"🟢 *Работают:* {stats['working']}\\n\"\n",
    "            f\"🟡 *Не работают:* {stats['not_working']}\\n\"\n",
    "            f\"🔴 *Уволены:* {stats['fired']}\\n\"\n",
    "            f\"✨ *Новые (30 дней):* {stats['new_last_30_days']}\\n\"\n",
    "            f\"📊 *Среднее кол-во заказов:* {stats['avg_orders']}\\n\"\n",
    "        )\n",
    "        \n",
    "        # Добавляем информацию о последнем сборе\n",
    "        last_log = crud.get_last_collection_log(db)\n",
    "        if last_log:\n",
    "            response += f\"\\n🔄 *Последнее обновление:*\\n\"\n",
    "            response += f\"   • {last_log.finished_at.strftime('%Y-%m-%d %H:%M')}\\n\"\n",
    "            response += f\"   • Новых: {last_log.new_drivers_added}\\n\"\n",
    "            response += f\"   • Обновлено статусов: {last_log.status_updated}\\n\"\n",
    "            response += f\"   • Обновлено заказов: {last_log.orders_updated}\\n\"\n",
    "        \n",
    "        await update.message.reply_text(response, parse_mode='Markdown')\n",
    "        \n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "async def get_top_drivers(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /top - топ водителей по заказам\"\"\"\n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        # Получаем топ-10 работающих водителей\n",
    "        drivers = db.query(models.Driver).filter(\n",
    "            models.Driver.work_status == 'working'\n",
    "        ).order_by(\n",
    "            models.Driver.orders_count.desc()\n",
    "        ).limit(10).all()\n",
    "        \n",
    "        if not drivers:\n",
    "            await update.message.reply_text(\"Нет данных о водителях\")\n",
    "            return\n",
    "        \n",
    "        response = \"🏆 *Топ-10 водителей по заказам:*\\n\\n\"\n",
    "        for i, driver in enumerate(drivers, 1):\n",
    "            response += f\"{i}. {driver.first_name} {driver.last_name}\\n\"\n",
    "            response += f\"   📦 Заказов: {driver.orders_count}\\n\"\n",
    "            if driver.work_status == 'working':\n",
    "                response += f\"   🟢 Статус: Работает\\n\"\n",
    "            response += \"\\n\"\n",
    "        \n",
    "        await update.message.reply_text(response[:4096], parse_mode='Markdown')\n",
    "        \n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "async def search_driver(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /search <имя или ID>\"\"\"\n",
    "    if not context.args:\n",
    "        await update.message.reply_text(\n",
    "            \"❓ Укажите имя или ID водителя\\n\"\n",
    "            \"Пример: /search Иван\"\n",
    "        )\n",
    "        return\n",
    "    \n",
    "    query = ' '.join(context.args)\n",
    "    await update.message.reply_text(f\"🔍 Ищу: {query}...\")\n",
    "    \n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        drivers = crud.search_drivers(db, query)\n",
    "        \n",
    "        if not drivers:\n",
    "            await update.message.reply_text(f\"Водители по запросу '{query}' не найдены\")\n",
    "            return\n",
    "        \n",
    "        response = f\"🔍 *Результаты поиска:*\\n\\n\"\n",
    "        for driver in drivers[:10]:\n",
    "            response += f\"👤 {driver.first_name} {driver.last_name}\\n\"\n",
    "            response += f\"   🆔 ID: `{driver.driver_id[:12]}...`\\n\"\n",
    "            response += f\"   📦 Заказов: {driver.orders_count}\\n\"\n",
    "            status_emoji = \"🟢\" if driver.work_status == \"working\" else \"🟡\" if driver.work_status == \"not_working\" else \"🔴\"\n",
    "            response += f\"   {status_emoji} Статус: {driver.work_status}\\n\\n\"\n",
    "        \n",
    "        await update.message.reply_text(response[:4096], parse_mode='Markdown')\n",
    "        \n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "async def get_new_drivers(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /new - новые водители\"\"\"\n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        cutoff = datetime.utcnow() - timedelta(days=30)\n",
    "        \n",
    "        drivers = db.query(models.Driver).filter(\n",
    "            models.Driver.created_at >= cutoff\n",
    "        ).order_by(\n",
    "            models.Driver.created_at.desc()\n",
    "        ).limit(20).all()\n",
    "        \n",
    "        if not drivers:\n",
    "            await update.message.reply_text(\"Нет новых водителей за последние 30 дней\")\n",
    "            return\n",
    "        \n",
    "        response = \"✨ *Новые водители (последние 30 дней):*\\n\\n\"\n",
    "        for driver in drivers:\n",
    "            response += f\"👤 {driver.first_name} {driver.last_name}\\n\"\n",
    "            response += f\"   📅 Добавлен: {driver.created_at.strftime('%Y-%m-%d')}\\n\"\n",
    "            response += f\"   📦 Заказов: {driver.orders_count}\\n\\n\"\n",
    "        \n",
    "        await update.message.reply_text(response[:4096], parse_mode='Markdown')\n",
    "        \n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "async def get_drivers_by_status(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /status <working/not_working/fired>\"\"\"\n",
    "    if not context.args:\n",
    "        await update.message.reply_text(\n",
    "            \"❓ Укажите статус\\n\"\n",
    "            \"Варианты: working, not_working, fired\\n\"\n",
    "            \"Пример: /status working\"\n",
    "        )\n",
    "        return\n",
    "    \n",
    "    status = context.args[0].lower()\n",
    "    if status not in ['working', 'not_working', 'fired']:\n",
    "        await update.message.reply_text(\"Неверный статус. Используйте: working, not_working или fired\")\n",
    "        return\n",
    "    \n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        drivers = crud.get_drivers_by_status(db, status)\n",
    "        \n",
    "        status_emoji = \"🟢\" if status == \"working\" else \"🟡\" if status == \"not_working\" else \"🔴\"\n",
    "        response = f\"{status_emoji} *Водители со статусом '{status}':*\\n\\n\"\n",
    "        \n",
    "        for driver in drivers[:20]:\n",
    "            response += f\"👤 {driver.first_name} {driver.last_name}\\n\"\n",
    "            response += f\"   📦 Заказов: {driver.orders_count}\\n\"\n",
    "            if driver.last_updated:\n",
    "                days_ago = (datetime.utcnow() - driver.last_updated).days\n",
    "                response += f\"   🕒 Обновлен: {days_ago} дней назад\\n\"\n",
    "            response += \"\\n\"\n",
    "        \n",
    "        if len(drivers) > 20:\n",
    "            response += f\"\\n*... и еще {len(drivers) - 20} водителей*\"\n",
    "        \n",
    "        await update.message.reply_text(response[:4096], parse_mode='Markdown')\n",
    "        \n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "async def get_driver_info(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /driver <id> - информация о водителе\"\"\"\n",
    "    if not context.args:\n",
    "        await update.message.reply_text(\n",
    "            \"❓ Укажите ID водителя\\n\"\n",
    "            \"Пример: /driver 123456789\"\n",
    "        )\n",
    "        return\n",
    "    \n",
    "    driver_id = context.args[0]\n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        driver = crud.get_driver(db, driver_id)\n",
    "        \n",
    "        if not driver:\n",
    "            await update.message.reply_text(f\"Водитель с ID {driver_id} не найден\")\n",
    "            return\n",
    "        \n",
    "        status_emoji = \"🟢\" if driver.work_status == \"working\" else \"🟡\" if driver.work_status == \"not_working\" else \"🔴\"\n",
    "        \n",
    "        response = (\n",
    "            f\"👤 *Информация о водителе:*\\n\\n\"\n",
    "            f\"*Имя:* {driver.first_name} {driver.last_name}\\n\"\n",
    "            f\"*ID:* `{driver.driver_id}`\\n\"\n",
    "            f\"*Статус:* {status_emoji} {driver.work_status}\\n\"\n",
    "            f\"*Заказов:* 📦 {driver.orders_count}\\n\"\n",
    "            f\"*Баланс:* 💰 {driver.balance} {driver.currency}\\n\"\n",
    "            f\"*Текущий статус:* {driver.current_status}\\n\"\n",
    "        )\n",
    "        \n",
    "        if driver.created_date:\n",
    "            response += f\"*Дата регистрации:* {driver.created_date[:10]}\\n\"\n",
    "        \n",
    "        if driver.last_transaction_date:\n",
    "            response += f\"*Последняя транзакция:* {driver.last_transaction_date[:10]}\\n\"\n",
    "        \n",
    "        if driver.last_updated:\n",
    "            days_ago = (datetime.utcnow() - driver.last_updated).days\n",
    "            response += f\"*Последнее обновление:* {days_ago} дней назад\\n\"\n",
    "        \n",
    "        await update.message.reply_text(response, parse_mode='Markdown')\n",
    "        \n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "async def get_recent_updates(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /recent - последние обновления\"\"\"\n",
    "    db = SessionLocal()\n",
    "    try:\n",
    "        logs = crud.get_collection_history(db, limit=5)\n",
    "        \n",
    "        if not logs:\n",
    "            await update.message.reply_text(\"Нет данных об обновлениях\")\n",
    "            return\n",
    "        \n",
    "        response = \"🔄 *Последние обновления:*\\n\\n\"\n",
    "        for log in logs:\n",
    "            status_emoji = \"✅\" if log.status == \"success\" else \"❌\"\n",
    "            response += f\"{status_emoji} *{log.finished_at.strftime('%Y-%m-%d %H:%M')}*\\n\"\n",
    "            if log.status == \"success\":\n",
    "                response += f\"   ✨ Новых: {log.new_drivers_added}\\n\"\n",
    "                response += f\"   🔄 Обновлено статусов: {log.status_updated}\\n\"\n",
    "                response += f\"   📊 Обновлено заказов: {log.orders_updated}\\n\"\n",
    "            else:\n",
    "                response += f\"   ⚠️ Ошибка: {log.error_message}\\n\"\n",
    "            response += \"\\n\"\n",
    "        \n",
    "        await update.message.reply_text(response, parse_mode='Markdown')\n",
    "        \n",
    "    finally:\n",
    "        db.close()\n",
    "\n",
    "async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Команда /help\"\"\"\n",
    "    help_text = \"\"\"\n",
    "📚 *Подробная справка по командам:*\n",
    "\n",
    "/stats - Общая статистика\n",
    "   • Количество водителей по статусам\n",
    "   • Среднее количество заказов\n",
    "   • Информация о последнем обновлении\n",
    "\n",
    "/top - Топ-10 работающих водителей по заказам\n",
    "\n",
    "/search <имя или ID> - Поиск водителей\n",
    "   • Поиск по имени или ID\n",
    "   • Показывает первые 10 результатов\n",
    "\n",
    "/new - Новые водители\n",
    "   • Показывает водителей, добавленных за последние 30 дней\n",
    "\n",
    "/status <working/not_working/fired> - Водители по статусу\n",
    "   • Показывает до 20 водителей с указанным статусом\n",
    "\n",
    "/driver <id> - Информация о конкретном водителе\n",
    "   • Полная информация: имя, статус, заказы, баланс\n",
    "\n",
    "/recent - История обновлений\n",
    "   • Показывает последние 5 запусков сборщика\n",
    "\n",
    "/help - Эта справка\n",
    "\n",
    "*Примеры использования:*\n",
    "/search Иван\n",
    "/status working\n",
    "/driver 123456789\n",
    "\"\"\"\n",
    "    await update.message.reply_text(help_text, parse_mode='Markdown')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
